<?php

/**
 * @file
 * Primary module hooks for Adimeo event module.
 */

declare(strict_types=1);

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\datetime\Plugin\Field\FieldType\DateTimeItemInterface;

/**
 * Implements hook_cron().
 */
function custom_event_cron(): void {
  $current_date = new \DateTime('now');
  $current_date = DrupalDateTime::createFromDateTime($current_date);
  $query = Drupal::entityTypeManager()->getStorage('node')->getQuery()
    ->latestRevision()
    ->accessCheck(TRUE)
    ->condition('type', 'event')
    ->condition('status', 1)
    ->sort('field_date_range', 'ASC')
    ->condition('field_date_range.end_value', $current_date->format(DateTimeItemInterface::DATETIME_STORAGE_FORMAT), '<=');
  $nids = $query->execute();

  /** @var \Drupal\Core\Queue\QueueFactory $queue_factory */
  $queue_factory = \Drupal::service('queue');
  $queue = $queue_factory->get('event_cron_queue_worker');

  foreach ($nids as $nid) {
    $node = Drupal::entityTypeManager()->getStorage('node')->load($nid);
    $queue->createItem($node);
  }

}
